version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Australia/Sydney
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 5
  labels:
    - "dependencies"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Australia/Sydney
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 5
  labels:
    - "dependencies"
